# Generated by Django 2.2.7 on 2019-11-22 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=15)),
                ('group_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('dob', models.DateTimeField(verbose_name='Date of Birth')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20)),
                ('pass_cipher', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserMemberLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupsapp.Member')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupsapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='MemberGroupLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupsapp.Group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupsapp.Member')),
            ],
        ),
        migrations.CreateModel(
            name='GroupGroupLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Group1', to='groupsapp.Group')),
                ('group2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Group2', to='groupsapp.Group')),
            ],
        ),
    ]
