# Generated by Django 2.2.7 on 2019-11-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupsapp', '0003_joincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joincode',
            name='code',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
