# Generated by Django 2.2.7 on 2019-11-30 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupsapp', '0004_auto_20191130_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joincode',
            old_name='maxNo',
            new_name='maxno',
        ),
    ]
