# Generated by Django 2.2.7 on 2019-12-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupsapp', '0005_auto_20191130_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_type',
            field=models.CharField(choices=[('SE', 'Section'), ('GR', 'Group'), ('DI', 'District'), ('CO', 'County')], max_length=2),
        ),
    ]
