# Generated by Django 2.2.7 on 2020-01-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupsapp', '0008_auto_20191205_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_user',
            field=models.BooleanField(default=False),
        ),
    ]
