# Generated by Django 2.2.7 on 2020-02-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupsapp', '0009_member_is_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='is_user',
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Unknown: Not Set')], default='U', max_length=1),
        ),
    ]
