# Generated by Django 2.2.7 on 2020-01-29 11:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('groupsapp', '0011_auto_20200129_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='dob',
        ),
        migrations.AddField(
            model_name='member',
            name='Date of Birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
