# Generated by Django 2.2.7 on 2020-01-29 11:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('groupsapp', '0012_auto_20200129_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='Date of Birth',
        ),
        migrations.AddField(
            model_name='member',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of Birth'),
            preserve_default=False,
        ),
    ]
