# Generated by Django 2.2.7 on 2020-02-08 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupsapp', '0013_auto_20200129_1156'),
        ('groupsapp', '0010_auto_20200208_1152'),
    ]

    operations = [
    ]
