# Generated by Django 2.2.7 on 2020-02-18 10:40

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('groupsapp', '0014_merge_20200208_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='dob',
            field=encrypted_model_fields.fields.EncryptedDateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=encrypted_model_fields.fields.EncryptedCharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Unknown: Not Set')], default='U'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
