# Generated by Django 2.2.7 on 2020-04-01 15:13

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('groupsapp', '0017_auto_20200323_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=encrypted_model_fields.fields.EncryptedCharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='U'),
        ),
    ]
